name: Build Codjixd Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, x86]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shc gcc

      - name: Compile script for ${{ matrix.arch }}
        run: |
          mkdir -p dist
          shc -f codjixd.sh -o ./dist/codjixd-linux-${{ matrix.arch }}

      - name: Verify binaries
        run: |
          ./dist/codjixd-linux-${{ matrix.arch }} --version

      - name: Draft a new release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/codjixd-linux-*
